# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true


font:
  size: 12
 
  normal:
    family: Monaco
    style: Regular
 
  bold:
    family: Monaco
    style: Bold
 
  italic:
    family: Monaco
    style: italic


#关闭title bar
window:
  decorations: "none"


#主题
colors:
  bright:
    black: '#333333'
    blue: '#4477e7'
    cyan: '#82c4c4'
    green: '#aad8aa'
    magenta: '#d8b6d8'
    red: '#f97b58'
    white: '#ffffff'
    yellow: '#fac761'
  cursor:
    cursor: '#fcbb6a'
    text: '#ffffff'
  normal:
    black: '#000000'
    blue: '#4477e7'
    cyan: '#5fb4b4'
    green: '#77d877'
    magenta: '#c695c6'
    red: '#ec5f66'
    white: '#f7f7f7'
    yellow: '#f9ae58'
  primary:
    background: '#343d46'
    foreground: '#d8dee9'
  selection:
    background: '#4e5a65'
    text: '#d8dee9'
